language: elixir
elixir:
  - 1.9.1
otp_release:
  - 22.0.7
script:
  - MIX_ENV=test mix do compile --warnings-as-errors, coveralls.json

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: false
